/*
  Warnings:

  - You are about to drop the column `average` on the `ExpectSchool` table. All the data in the column will be lost.
  - You are about to drop the column `rate` on the `ExpectSchool` table. All the data in the column will be lost.
  - You are about to drop the column `score` on the `ExpectSchool` table. All the data in the column will be lost.
  - You are about to drop the column `type` on the `ExpectSchool` table. All the data in the column will be lost.
  - You are about to drop the column `unit` on the `ExpectSchool` table. All the data in the column will be lost.
  - You are about to drop the `ExprectExam` table. If the table is not empty, all the data it contains will be lost.
  - Added the required column `type` to the `ExpectStudent` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE `ExprectExam` DROP FOREIGN KEY `ExprectExam_subjectId_fkey`;

-- DropForeignKey
ALTER TABLE `ExprectExam` DROP FOREIGN KEY `ExprectExam_userId_fkey`;

-- AlterTable
ALTER TABLE `ExpectSchool` DROP COLUMN `average`,
    DROP COLUMN `rate`,
    DROP COLUMN `score`,
    DROP COLUMN `type`,
    DROP COLUMN `unit`,
    ADD COLUMN `averageRate` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `averageScore` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `beforeExpectScore` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `expectScore` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `first1FinalAverage` INTEGER NULL,
    ADD COLUMN `first1FinalName` VARCHAR(191) NULL,
    ADD COLUMN `first1FinalRate` INTEGER NULL,
    ADD COLUMN `first1FinalScore` INTEGER NULL,
    ADD COLUMN `first1FinalUnit` INTEGER NULL,
    ADD COLUMN `first1MidAverage` INTEGER NULL,
    ADD COLUMN `first1MidName` VARCHAR(191) NULL,
    ADD COLUMN `first1MidRate` INTEGER NULL,
    ADD COLUMN `first1MidScore` INTEGER NULL,
    ADD COLUMN `first1MidUnit` INTEGER NULL,
    ADD COLUMN `first2FinalAverage` INTEGER NULL,
    ADD COLUMN `first2FinalName` VARCHAR(191) NULL,
    ADD COLUMN `first2FinalRate` INTEGER NULL,
    ADD COLUMN `first2FinalScore` INTEGER NULL,
    ADD COLUMN `first2FinalUnit` INTEGER NULL,
    ADD COLUMN `first2MidAverage` INTEGER NULL,
    ADD COLUMN `first2MidName` VARCHAR(191) NULL,
    ADD COLUMN `first2MidRate` INTEGER NULL,
    ADD COLUMN `first2MidScore` INTEGER NULL,
    ADD COLUMN `first2MidUnit` INTEGER NULL,
    ADD COLUMN `second1FinalAverage` INTEGER NULL,
    ADD COLUMN `second1FinalName` VARCHAR(191) NULL,
    ADD COLUMN `second1FinalRate` INTEGER NULL,
    ADD COLUMN `second1FinalScore` INTEGER NULL,
    ADD COLUMN `second1FinalUnit` INTEGER NULL,
    ADD COLUMN `second1MidAverage` INTEGER NULL,
    ADD COLUMN `second1MidName` VARCHAR(191) NULL,
    ADD COLUMN `second1MidRate` INTEGER NULL,
    ADD COLUMN `second1MidScore` INTEGER NULL,
    ADD COLUMN `second1MidUnit` INTEGER NULL,
    ADD COLUMN `second2FinalAverage` INTEGER NULL,
    ADD COLUMN `second2FinalName` VARCHAR(191) NULL,
    ADD COLUMN `second2FinalRate` INTEGER NULL,
    ADD COLUMN `second2FinalScore` INTEGER NULL,
    ADD COLUMN `second2FinalUnit` INTEGER NULL,
    ADD COLUMN `second2MidAverage` INTEGER NULL,
    ADD COLUMN `second2MidName` VARCHAR(191) NULL,
    ADD COLUMN `second2MidRate` INTEGER NULL,
    ADD COLUMN `second2MidScore` INTEGER NULL,
    ADD COLUMN `second2MidUnit` INTEGER NULL,
    ADD COLUMN `third1FinalAverage` INTEGER NULL,
    ADD COLUMN `third1FinalName` VARCHAR(191) NULL,
    ADD COLUMN `third1FinalRate` INTEGER NULL,
    ADD COLUMN `third1FinalScore` INTEGER NULL,
    ADD COLUMN `third1FinalUnit` INTEGER NULL,
    ADD COLUMN `third1MidAverage` INTEGER NULL,
    ADD COLUMN `third1MidName` VARCHAR(191) NULL,
    ADD COLUMN `third1MidRate` INTEGER NULL,
    ADD COLUMN `third1MidScore` INTEGER NULL,
    ADD COLUMN `third1MidUnit` INTEGER NULL,
    ADD COLUMN `third2FinalAverage` INTEGER NULL,
    ADD COLUMN `third2FinalName` VARCHAR(191) NULL,
    ADD COLUMN `third2FinalRate` INTEGER NULL,
    ADD COLUMN `third2FinalScore` INTEGER NULL,
    ADD COLUMN `third2FinalUnit` INTEGER NULL,
    ADD COLUMN `third2MidAverage` INTEGER NULL,
    ADD COLUMN `third2MidName` VARCHAR(191) NULL,
    ADD COLUMN `third2MidRate` INTEGER NULL,
    ADD COLUMN `third2MidScore` INTEGER NULL,
    ADD COLUMN `third2MidUnit` INTEGER NULL;

-- AlterTable
ALTER TABLE `ExpectStudent` ADD COLUMN `activity` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `career` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `careerRelevance` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `community` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `first1Ability` INTEGER NULL,
    ADD COLUMN `first1CareerRelevance` INTEGER NULL,
    ADD COLUMN `first1Impression` VARCHAR(191) NULL,
    ADD COLUMN `first1Meter` VARCHAR(191) NULL,
    ADD COLUMN `first1Name` VARCHAR(191) NULL,
    ADD COLUMN `first1Process` VARCHAR(191) NULL,
    ADD COLUMN `first1Satisfaction` INTEGER NULL,
    ADD COLUMN `first1Topic` VARCHAR(191) NULL,
    ADD COLUMN `first2Ability` INTEGER NULL,
    ADD COLUMN `first2CareerRelevance` INTEGER NULL,
    ADD COLUMN `first2Impression` VARCHAR(191) NULL,
    ADD COLUMN `first2Meter` VARCHAR(191) NULL,
    ADD COLUMN `first2Name` VARCHAR(191) NULL,
    ADD COLUMN `first2Process` VARCHAR(191) NULL,
    ADD COLUMN `first2Satisfaction` INTEGER NULL,
    ADD COLUMN `first2Topic` VARCHAR(191) NULL,
    ADD COLUMN `satisfaction` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `second1Ability` VARCHAR(191) NULL,
    ADD COLUMN `second1CareerRelevance` INTEGER NULL,
    ADD COLUMN `second1Impression` VARCHAR(191) NULL,
    ADD COLUMN `second1Meter` VARCHAR(191) NULL,
    ADD COLUMN `second1Name` VARCHAR(191) NULL,
    ADD COLUMN `second1Process` VARCHAR(191) NULL,
    ADD COLUMN `second1Satisfaction` INTEGER NULL,
    ADD COLUMN `second1Topic` VARCHAR(191) NULL,
    ADD COLUMN `second2Ability` VARCHAR(191) NULL,
    ADD COLUMN `second2CareerRelevance` INTEGER NULL,
    ADD COLUMN `second2Impression` VARCHAR(191) NULL,
    ADD COLUMN `second2Meter` VARCHAR(191) NULL,
    ADD COLUMN `second2Name` VARCHAR(191) NULL,
    ADD COLUMN `second2Process` VARCHAR(191) NULL,
    ADD COLUMN `second2Satisfaction` INTEGER NULL,
    ADD COLUMN `second2Topic` VARCHAR(191) NULL,
    ADD COLUMN `study` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `third1Ability` INTEGER NULL,
    ADD COLUMN `third1CareerRelevance` INTEGER NULL,
    ADD COLUMN `third1Impression` VARCHAR(191) NULL,
    ADD COLUMN `third1Meter` VARCHAR(191) NULL,
    ADD COLUMN `third1Name` VARCHAR(191) NULL,
    ADD COLUMN `third1Process` VARCHAR(191) NULL,
    ADD COLUMN `third1Satisfaction` INTEGER NULL,
    ADD COLUMN `third1Topic` VARCHAR(191) NULL,
    ADD COLUMN `third2Ability` INTEGER NULL,
    ADD COLUMN `third2CareerRelevance` INTEGER NULL,
    ADD COLUMN `third2Impression` VARCHAR(191) NULL,
    ADD COLUMN `third2Meter` VARCHAR(191) NULL,
    ADD COLUMN `third2Name` VARCHAR(191) NULL,
    ADD COLUMN `third2Process` VARCHAR(191) NULL,
    ADD COLUMN `third2Satisfaction` INTEGER NULL,
    ADD COLUMN `third2Topic` VARCHAR(191) NULL,
    ADD COLUMN `type` VARCHAR(191) NOT NULL;

-- DropTable
DROP TABLE `ExprectExam`;

-- CreateTable
CREATE TABLE `ExpectExam` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `subjectId` INTEGER NOT NULL,
    `averageScore` INTEGER NOT NULL DEFAULT 0,
    `averageRate` INTEGER NOT NULL DEFAULT 0,
    `expectScore` INTEGER NOT NULL DEFAULT 0,
    `beforeExpectScore` INTEGER NOT NULL DEFAULT 0,
    `first1Name` VARCHAR(191) NULL,
    `first1Date` DATETIME(3) NULL,
    `first1Institute` VARCHAR(191) NULL,
    `first1Score` INTEGER NULL,
    `first1Average` INTEGER NULL,
    `first1Unit` INTEGER NULL,
    `first1Rate` INTEGER NULL,
    `first1Percent` INTEGER NULL,
    `first1StandardScore` INTEGER NULL,
    `first2Name` VARCHAR(191) NULL,
    `first2Date` DATETIME(3) NULL,
    `first2Institute` VARCHAR(191) NULL,
    `first2Score` INTEGER NULL,
    `first2Average` INTEGER NULL,
    `first2Unit` INTEGER NULL,
    `first2Rate` INTEGER NULL,
    `first2Percent` INTEGER NULL,
    `first2StandardScore` INTEGER NULL,
    `first3Name` VARCHAR(191) NULL,
    `first3Date` DATETIME(3) NULL,
    `first3Institute` VARCHAR(191) NULL,
    `first3Score` INTEGER NULL,
    `first3Average` INTEGER NULL,
    `first3Unit` INTEGER NULL,
    `first3Rate` INTEGER NULL,
    `first3Percent` INTEGER NULL,
    `first3StandardScore` INTEGER NULL,
    `second1Name` VARCHAR(191) NULL,
    `second1Date` DATETIME(3) NULL,
    `second1Institute` VARCHAR(191) NULL,
    `second1Score` INTEGER NULL,
    `second1Average` INTEGER NULL,
    `second1Unit` INTEGER NULL,
    `second1Rate` INTEGER NULL,
    `second1Percent` INTEGER NULL,
    `second1StandardScore` INTEGER NULL,
    `second2Name` VARCHAR(191) NULL,
    `second2Date` DATETIME(3) NULL,
    `second2Institute` VARCHAR(191) NULL,
    `second2Score` INTEGER NULL,
    `second2Average` INTEGER NULL,
    `second2Unit` INTEGER NULL,
    `second2Rate` INTEGER NULL,
    `second2Percent` INTEGER NULL,
    `second2StandardScore` INTEGER NULL,
    `second3Name` VARCHAR(191) NULL,
    `second3Date` DATETIME(3) NULL,
    `second3Institute` VARCHAR(191) NULL,
    `second3Score` INTEGER NULL,
    `second3Average` INTEGER NULL,
    `second3Unit` INTEGER NULL,
    `second3Rate` INTEGER NULL,
    `second3Percent` INTEGER NULL,
    `second3StandardScore` INTEGER NULL,
    `third1Name` VARCHAR(191) NULL,
    `third1Date` DATETIME(3) NULL,
    `third1Institute` VARCHAR(191) NULL,
    `third1Score` INTEGER NULL,
    `third1Average` INTEGER NULL,
    `third1Unit` INTEGER NULL,
    `third1Rate` INTEGER NULL,
    `third1Percent` INTEGER NULL,
    `third1StandardScore` INTEGER NULL,
    `third2Name` VARCHAR(191) NULL,
    `third2Date` DATETIME(3) NULL,
    `third2Institute` VARCHAR(191) NULL,
    `third2Score` INTEGER NULL,
    `third2Average` INTEGER NULL,
    `third2Unit` INTEGER NULL,
    `third2Rate` INTEGER NULL,
    `third2Percent` INTEGER NULL,
    `third2StandardScore` INTEGER NULL,
    `third3Name` VARCHAR(191) NULL,
    `third3Date` DATETIME(3) NULL,
    `third3Institute` VARCHAR(191) NULL,
    `third3Score` INTEGER NULL,
    `third3Average` INTEGER NULL,
    `third3Unit` INTEGER NULL,
    `third3Rate` INTEGER NULL,
    `third3Percent` INTEGER NULL,
    `third3StandardScore` INTEGER NULL,
    `createDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updateDate` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ExpectExam` ADD CONSTRAINT `ExpectExam_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ExpectExam` ADD CONSTRAINT `ExpectExam_subjectId_fkey` FOREIGN KEY (`subjectId`) REFERENCES `Subject`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
